// Created by Jura Skrlec on 23.05.2023..
// Copyright (c) 2023 Microblink Ltd. All rights reserved.

// ANY UNAUTHORIZED USE OR SALE, DUPLICATION, OR DISTRIBUTION
// OF THIS PROGRAM OR ANY OF ITS PARTS, IN SOURCE OR BINARY FORMS,
// WITH OR WITHOUT MODIFICATION, WITH THE PURPOSE OF ACQUIRING
// UNLAWFUL MATERIAL OR ANY OTHER BENEFIT IS PROHIBITED!
// THIS PROGRAM IS PROTECTED BY COPYRIGHT LAWS AND YOU MAY NOT
// REVERSE ENGINEER, DECOMPILE, OR DISASSEMBLE IT.

#import <CaptureCore/MBCCImage.h>

NS_ASSUME_NONNULL_BEGIN

/// Image of a cropped and perspective-corrected document.
MBCC_CORE_FINAL
@interface MBCCTransformedImage : MBCCImage

- (instancetype)init NS_UNAVAILABLE;

@end

NS_ASSUME_NONNULL_END
